Initial Implementation (#58)
* Fixed `format` script

Updated repository URL as well

* Added GitVersion config

* Removed unused template file

* Added interaface for NuGet registry

* Added additional packages

Added actions/exec to run CLI tools
Added ajv to validate schema of JSON argument for action

* Updated actions metadata

Addeda author deatils
Updated inputs to allow a JSON string to be passed into the action

* Updated prettier to put space around brackets

* Increased width for TS lines

* Added command to run local tests

This makes it faster to run tests without dealing with linting
Speeds up local development
Added references to Jest to improve testing

* Created NuGet service to handle all NuGet CLI commands

Updated main entrypoint to use new service
This also addresses previous issues with running unit tests
The use of Ajv was incorrect causing errors

* Updated unit tests

Added additional coverage for the new NuGet service

* Built latest version of action

* Removed boiler plate stuff from README.md

* Updated with npm audit fix

* Upgraded prettier

* Removed comment from file

* Add logic to test the action in a workflow

* Began documenting action in README.md

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -19,6 +19,22 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
+      
       - uses: ./
         with:
-          milliseconds: 1000
+          serializedNuGetRegistries: '[{"name":"unit test","password":"P@$$w0rd","url":"https://nuget.myfeed.local","username":"nuget-user"}]'
+
+      - run: |
+          # Primer, to ensure the welcome and telemetry messages are not shown
+          dotnet --version
+          
+          # List the NuGet sources to file
+          # This makes it easier to grep for the sources
+          dotnet nuget list source >> output
+
+          if grep -q "https://nuget.myfeed.local" output; then
+            echo "Found"
+          else
+            echo "Not Found"
+          	exit 1
+          fi
